# Generated by Django 4.2 on 2023-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("helpy", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Helper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vip", models.BooleanField(default=False)),
                ("contacts", models.TextField()),
                ("user_offer_is_free", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("soft_skills", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("languages", models.ManyToManyField(to="accounts.language")),
                ("regions", models.ManyToManyField(to="accounts.region")),
                ("support_levels", models.ManyToManyField(to="accounts.supportlevel")),
                ("tags", models.ManyToManyField(to="helpy.tag_help")),
            ],
        ),
    ]
