# Generated by Django 4.2 on 2023-04-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Re_view",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("helper_name", models.CharField(max_length=255)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("moto_rent", "Moto Rent"),
                            ("moto_beginner", "Moto Beginner"),
                            ("moto_sos", "Moto SOS"),
                            ("rent_estate", "Rent Estate"),
                            ("public_serv", "Public Service"),
                            ("lang_schol", "Language School"),
                            ("trabl", "Travel"),
                            ("med_help", "Medical Help"),
                            ("serv_transl", "Translation Services"),
                            ("shopping_destination", "Shopping Destination"),
                            ("clothing", "Clothing"),
                            ("food", "Food"),
                            ("souvenirs", "Souvenirs"),
                            ("ind_tour", "Individual Tour"),
                            ("escort", "Escort"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level_of_service",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")]
                    ),
                ),
                ("review_text", models.TextField()),
                ("wishes", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "helper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="offer.helper"
                    ),
                ),
            ],
        ),
    ]
