# Generated by Django 4.2 on 2023-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="re_view",
            name="tag",
            field=models.CharField(
                choices=[
                    ("moto_rent", "Moto Rent"),
                    ("moto_beginner", "Moto Beginner"),
                    ("moto_sos", "Moto SOS"),
                    ("rent_estate", "Rent Estate"),
                    ("public_serv", "Public Service"),
                    ("lang_schol", "Language School"),
                    ("trabl", "Travel"),
                    ("med_help", "Medical Help"),
                    ("serv_transl", "Translation Services"),
                    ("shopping_destination", "Shopping Destination"),
                    ("clothing", "Clothing"),
                    ("food", "Food"),
                    ("souvenirs", "Souvenirs"),
                    ("ind_tour", "Individual Tour"),
                    ("escort", "Escort"),
                ],
                max_length=100,
            ),
        ),
    ]
