# Generated by Django 4.2 on 2023-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_re_view_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="re_view",
            name="tag",
            field=models.CharField(
                choices=[
                    ("moto_rent", "Moto Rent"),
                    ("moto_beginner", "Moto Beginner"),
                    ("moto_sos", "Moto SOS"),
                    ("rent_estate", "Rent Estate"),
                    ("public_serv", "Public Service"),
                    ("lang_schol", "Language School"),
                    ("med_help", "Medical Help"),
                    ("serv_transl", "Translation Services"),
                    ("shopping_destination", "Shopping Destination"),
                    ("souvenirs", "Souvenirs"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(max_length=255),
        ),
    ]
