# Generated by Django 4.2 on 2023-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag_article",
            name="name",
            field=models.CharField(
                choices=[
                    ("moto_rent", "Moto Rent"),
                    ("moto_beginner", "Moto Beginner"),
                    ("moto_sos", "Moto SOS"),
                    ("rent_estate", "Rent Estate"),
                    ("public_serv", "Public Service"),
                    ("lang_schol", "Language School"),
                    ("med_help", "Medical Help"),
                    ("serv_transl", "Translation Services"),
                    ("shopping_destination", "Shopping Destination"),
                    ("souvenirs", "Souvenirs"),
                ],
                default="moto_rent",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
