# Generated by Django 4.2 on 2023-05-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_event", "0004_alter_article_tags_alter_event_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                to="art_event.tag_article", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                to="art_event.tag_article", verbose_name="Tags"
            ),
        ),
    ]
