# Generated by Django 4.2 on 2023-05-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("helpy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("helper_nickname", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "selected_service",
                    models.CharField(
                        choices=[
                            ("moto_rent", "Moto Rent"),
                            ("moto_beginner", "Moto Beginner"),
                            ("moto_sos", "Moto SOS"),
                            ("rent_estate", "Rent Estate"),
                            ("public_serv", "Public Service"),
                            ("lang_schol", "Language School"),
                            ("trabl", "Travel"),
                            ("med_help", "Medical Help"),
                            ("serv_transl", "Translation Services"),
                            ("shopping_destination", "Shopping Destination"),
                            ("clothing", "Clothing"),
                            ("food", "Food"),
                            ("souvenirs", "Souvenirs"),
                            ("ind_tour", "Individual Tour"),
                            ("escort", "Escort"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level_of_help",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")]
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="helpy.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Re_view",
        ),
    ]
