# Generated by Django 4.2 on 2023-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpy", "0002_userrequest_delete_re_view"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag_help",
            options={"verbose_name": "Tag Help", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose all"),
                    ("Chaweng", "Chaweng"),
                    ("Lamai", "Lamai"),
                    ("Lipa Noi", "Lipa Noi"),
                    ("Nathon", "Nathon"),
                    ("Bang Bor", "Bang Bor"),
                    ("Maenam", "Maenam"),
                    ("Bophut", "Bophut"),
                    ("Choeng Mon", "Choeng Mon"),
                    ("Hua Thanon", "Hua Thanon"),
                ],
                default="Lamai",
                max_length=20,
            ),
        ),
    ]
