# Generated by Django 4.2 on 2023-05-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpy", "0003_alter_tag_help_options_alter_userrequest_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(
                choices=[
                    ("uk", "Українська"),
                    ("th", "ไทย"),
                    ("en", "English"),
                    ("fr", "Français"),
                    ("it", "Italiano"),
                    ("de", "Deutsch"),
                    ("ru", "Русский"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                choices=[
                    ("", "Choose all"),
                    ("Chaweng", "Chaweng"),
                    ("Lamai", "Lamai"),
                    ("Lipa Noi", "Lipa Noi"),
                    ("Nathon", "Nathon"),
                    ("Bang Bor", "Bang Bor"),
                    ("Maenam", "Maenam"),
                    ("Bophut", "Bophut"),
                    ("Choeng Mon", "Choeng Mon"),
                    ("Hua Thanon", "Hua Thanon"),
                ],
                max_length=55,
            ),
        ),
    ]
